"""Regression tests for issue #1729 -- stale CLAUDE.md never removed after
instructions move to .claude/rules/.

Acceptance criteria:
- Existing APM-generated CLAUDE.md + populated .claude/rules/ + apm compile --clean
  -> CLAUDE.md removed.
- Hand-authored CLAUDE.md (no marker) is NEVER removed; warning emitted instead.
- Plain apm compile (no --clean) still deletes nothing (non-destructive).
- Clean-checkout behavior from #1138 unchanged (no CLAUDE.md ever created when
  .claude/rules/ already populated).
- --no-dedup / --force-instructions still regenerate a full CLAUDE.md and never
  trigger removal.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from apm_cli.compilation.agents_compiler import AgentsCompiler, CompilationConfig
from apm_cli.compilation.claude_formatter import CLAUDE_HEADER
from apm_cli.compilation.constitution import clear_constitution_cache
from apm_cli.primitives.models import Instruction, PrimitiveCollection
from apm_cli.utils.path_security import PathTraversalError

# ---------------------------------------------------------------------------
# Module-level cache isolation
# ---------------------------------------------------------------------------


@pytest.fixture(autouse=True)
def _reset_constitution_cache():
    """Clear the module-level constitution cache before and after every test.

    The cache is global; without this fixture a test that places a constitution
    file on disk can leak state into later tests and cause unexpected
    CLAUDE.md emission or suppressed removal previews.
    """
    clear_constitution_cache()
    yield
    clear_constitution_cache()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


class _CapturingLogger:
    """Minimal logger stub that records (level, message) pairs for assertions."""

    def __init__(self):
        self.logged: list[tuple[str, str]] = []

    def progress(self, msg, **kw):
        self.logged.append(("progress", msg))

    def success(self, msg, **kw):
        self.logged.append(("success", msg))

    def warning(self, msg, **kw):
        self.logged.append(("warning", msg))

    def verbose_detail(self, msg, **kw):
        pass


def _make_project(tmp_path, *, populate_rules: bool = True):
    """Create a minimal project with an instruction primitive.

    If populate_rules=True a .claude/rules/*.md file is created so that
    _detect_deployed_instructions returns True (skip_instructions fires).
    """
    (tmp_path / "apm.yml").write_text(
        "name: test-stale-claude\nversion: 1.0.0\ntargets:\n  - claude\n",
        encoding="utf-8",
    )
    instr_dir = tmp_path / ".apm" / "instructions"
    instr_dir.mkdir(parents=True)
    (instr_dir / "global.instructions.md").write_text(
        "---\ndescription: A global instruction\n---\nThis is global guidance.\n",
        encoding="utf-8",
    )
    if populate_rules:
        rules_dir = tmp_path / ".claude" / "rules"
        rules_dir.mkdir(parents=True)
        (rules_dir / "global.md").write_text("This is global guidance.\n", encoding="utf-8")


def _apm_generated_claude_md(tmp_path) -> None:
    """Write a CLAUDE.md that looks like one generated by APM (has CLAUDE_HEADER)."""
    (tmp_path / "CLAUDE.md").write_text(
        f"{CLAUDE_HEADER}\n\n# Project Standards\n\nThis is global guidance.\n",
        encoding="utf-8",
    )


def _hand_authored_claude_md(tmp_path) -> None:
    """Write a CLAUDE.md without the APM marker (hand-authored)."""
    (tmp_path / "CLAUDE.md").write_text(
        "# My Custom Instructions\n\nHand-written content.\n",
        encoding="utf-8",
    )


def _make_primitives(tmp_path) -> PrimitiveCollection:
    primitives = PrimitiveCollection()
    primitives.add_primitive(
        Instruction(
            name="global",
            file_path=tmp_path / ".apm/instructions/global.instructions.md",
            description="A global instruction",
            apply_to="",
            content="This is global guidance.",
            author="test",
            source="local",
        )
    )
    return primitives


# ---------------------------------------------------------------------------
# Main acceptance criterion: --clean removes APM-generated stale CLAUDE.md
# ---------------------------------------------------------------------------


class TestCleanRemovesApmGeneratedStaleCLAUDEMD:
    """apm compile --clean must remove a stale APM-generated CLAUDE.md when
    instructions are already in .claude/rules/ (issue #1729 primary fix)."""

    def test_clean_removes_apm_generated_claude_md(self, tmp_path):
        """--clean + .claude/rules/ populated + APM-generated CLAUDE.md -> file removed."""
        _make_project(tmp_path, populate_rules=True)
        _apm_generated_claude_md(tmp_path)

        compiler = AgentsCompiler(str(tmp_path))
        config = CompilationConfig(
            target="claude",
            clean_orphaned=True,
            dry_run=False,
        )
        primitives = _make_primitives(tmp_path)
        result = compiler._compile_claude_md(config, primitives)

        assert result.success, f"Expected success, got errors: {result.errors}"
        assert not (tmp_path / "CLAUDE.md").exists(), (
            "APM-generated CLAUDE.md must be removed by --clean when .claude/rules/ is populated"
        )

    def test_clean_log_mentions_removal(self, tmp_path):
        """A success-level log about the removal must be emitted (green/bold)."""
        _make_project(tmp_path, populate_rules=True)
        _apm_generated_claude_md(tmp_path)

        logger = _CapturingLogger()
        compiler = AgentsCompiler(str(tmp_path))
        compiler._logger = logger
        config = CompilationConfig(
            target="claude",
            clean_orphaned=True,
            dry_run=False,
        )
        primitives = _make_primitives(tmp_path)
        compiler._compile_claude_md(config, primitives)

        # Must be logged at "success" level (green) -- a destructive file deletion
        # must render visibly distinct from an info/progress no-op (issue #1729 fix).
        success_messages = [m for level, m in logger.logged if level == "success"]
        assert any("Removed stale" in m and "CLAUDE.md" in m for m in success_messages), (
            f"Expected a 'Removed stale CLAUDE.md' log line at 'success' level, got: {logger.logged}"
        )

    def test_clean_checks_containment_before_unlink(self, tmp_path, monkeypatch):
        """Stale CLAUDE.md deletion must pass through the path containment guard."""
        _make_project(tmp_path, populate_rules=True)
        _apm_generated_claude_md(tmp_path)
        guard_calls = []

        def fake_ensure_path_within(path: Path, base_dir: Path) -> Path:
            guard_calls.append((path, base_dir))
            return path

        monkeypatch.setattr(
            "apm_cli.compilation.agents_compiler.ensure_path_within",
            fake_ensure_path_within,
        )

        compiler = AgentsCompiler(str(tmp_path))
        config = CompilationConfig(
            target="claude",
            clean_orphaned=True,
            dry_run=False,
        )
        primitives = _make_primitives(tmp_path)
        compiler._compile_claude_md(config, primitives)

        assert guard_calls == [
            (tmp_path / "CLAUDE.md", tmp_path),
            (tmp_path / "CLAUDE.md", tmp_path),
        ]
        assert not (tmp_path / "CLAUDE.md").exists()

    def test_clean_keeps_file_when_containment_guard_rejects(self, tmp_path, monkeypatch):
        """Containment failure must fail closed before reading or unlinking."""
        _make_project(tmp_path, populate_rules=True)
        _apm_generated_claude_md(tmp_path)

        def reject_path(path: Path, base_dir: Path) -> Path:
            raise PathTraversalError("outside base")

        monkeypatch.setattr("apm_cli.compilation.agents_compiler.ensure_path_within", reject_path)
        logger = _CapturingLogger()
        compiler = AgentsCompiler(str(tmp_path))
        compiler._logger = logger
        config = CompilationConfig(
            target="claude",
            clean_orphaned=True,
            dry_run=False,
        )
        primitives = _make_primitives(tmp_path)
        result = compiler._compile_claude_md(config, primitives)

        assert (tmp_path / "CLAUDE.md").exists()
        assert any("Could not read CLAUDE.md" in w for w in result.warnings)
        assert any(
            "Could not read CLAUDE.md" in m for level, m in logger.logged if level == "warning"
        )


# ---------------------------------------------------------------------------
# Hand-authored file protection
# ---------------------------------------------------------------------------


class TestHandAuthoredCLAUDEMDIsNeverRemoved:
    """A CLAUDE.md without the APM marker must NEVER be deleted."""

    def test_clean_does_not_delete_hand_authored_file(self, tmp_path):
        """--clean must NOT delete a hand-authored CLAUDE.md."""
        _make_project(tmp_path, populate_rules=True)
        _hand_authored_claude_md(tmp_path)
        original_content = (tmp_path / "CLAUDE.md").read_text(encoding="utf-8")

        compiler = AgentsCompiler(str(tmp_path))
        config = CompilationConfig(
            target="claude",
            clean_orphaned=True,
            dry_run=False,
        )
        primitives = _make_primitives(tmp_path)
        compiler._compile_claude_md(config, primitives)

        assert (tmp_path / "CLAUDE.md").exists(), (
            "Hand-authored CLAUDE.md must not be deleted by --clean"
        )
        assert (tmp_path / "CLAUDE.md").read_text(encoding="utf-8") == original_content, (
            "Hand-authored CLAUDE.md content must be unchanged"
        )

    def test_clean_emits_warning_for_hand_authored_file(self, tmp_path):
        """A warning must be emitted when a hand-authored CLAUDE.md blocks removal."""
        _make_project(tmp_path, populate_rules=True)
        _hand_authored_claude_md(tmp_path)

        compiler = AgentsCompiler(str(tmp_path))
        config = CompilationConfig(
            target="claude",
            clean_orphaned=True,
            dry_run=False,
        )
        primitives = _make_primitives(tmp_path)
        result = compiler._compile_claude_md(config, primitives)

        assert any("hand-authored" in w for w in result.warnings), (
            f"Expected a 'hand-authored' warning, got: {result.warnings}"
        )

    def test_clean_hand_authored_warning_emitted_via_logger(self, tmp_path):
        """Live --clean hand-authored skips must reach the terminal logger."""
        _make_project(tmp_path, populate_rules=True)
        _hand_authored_claude_md(tmp_path)

        logger = _CapturingLogger()
        compiler = AgentsCompiler(str(tmp_path))
        compiler._logger = logger
        config = CompilationConfig(
            target="claude",
            clean_orphaned=True,
            dry_run=False,
        )
        primitives = _make_primitives(tmp_path)
        compiler._compile_claude_md(config, primitives)

        warning_messages = [m for level, m in logger.logged if level == "warning"]
        assert any("hand-authored" in m and "CLAUDE.md" in m for m in warning_messages), (
            "Live --clean with a hand-authored CLAUDE.md must emit the skip warning "
            f"through the logger; got: {logger.logged}"
        )

    def test_clean_unlink_error_warning_emitted_via_logger(self, tmp_path, monkeypatch):
        """Live --clean unlink failures must be visible through the logger."""
        _make_project(tmp_path, populate_rules=True)
        _apm_generated_claude_md(tmp_path)

        def fail_unlink(self: Path) -> None:
            raise OSError("busy")

        monkeypatch.setattr(Path, "unlink", fail_unlink)
        logger = _CapturingLogger()
        compiler = AgentsCompiler(str(tmp_path))
        compiler._logger = logger
        config = CompilationConfig(
            target="claude",
            clean_orphaned=True,
            dry_run=False,
        )
        primitives = _make_primitives(tmp_path)
        result = compiler._compile_claude_md(config, primitives)

        assert (tmp_path / "CLAUDE.md").exists()
        assert any("Could not remove CLAUDE.md" in w for w in result.warnings)
        assert any(
            "Could not remove CLAUDE.md" in m for level, m in logger.logged if level == "warning"
        )


# ---------------------------------------------------------------------------
# Plain compile (no --clean) is non-destructive
# ---------------------------------------------------------------------------


class TestPlainCompileIsNonDestructive:
    """Plain apm compile (clean_orphaned=False) must never delete CLAUDE.md."""

    def test_plain_compile_leaves_apm_generated_claude_md(self, tmp_path):
        """Without --clean, an APM-generated stale CLAUDE.md must be left on disk."""
        _make_project(tmp_path, populate_rules=True)
        _apm_generated_claude_md(tmp_path)

        compiler = AgentsCompiler(str(tmp_path))
        config = CompilationConfig(
            target="claude",
            clean_orphaned=False,
            dry_run=False,
        )
        primitives = _make_primitives(tmp_path)
        compiler._compile_claude_md(config, primitives)

        assert (tmp_path / "CLAUDE.md").exists(), (
            "Plain apm compile must not remove CLAUDE.md -- only --clean may do that"
        )

    def test_plain_compile_leaves_hand_authored_claude_md(self, tmp_path):
        """Without --clean, a hand-authored CLAUDE.md must be left entirely alone."""
        _make_project(tmp_path, populate_rules=True)
        _hand_authored_claude_md(tmp_path)
        original_content = (tmp_path / "CLAUDE.md").read_text(encoding="utf-8")

        compiler = AgentsCompiler(str(tmp_path))
        config = CompilationConfig(
            target="claude",
            clean_orphaned=False,
            dry_run=False,
        )
        primitives = _make_primitives(tmp_path)
        compiler._compile_claude_md(config, primitives)

        assert (tmp_path / "CLAUDE.md").exists()
        assert (tmp_path / "CLAUDE.md").read_text(encoding="utf-8") == original_content

    def test_plain_compile_hand_authored_emits_no_warning(self, tmp_path):
        """Plain apm compile (no --clean) must emit NO 'Skipped removal' warning
        when a hand-authored CLAUDE.md coexists with a populated .claude/rules/
        directory.  The warning is misleading when no removal was even attempted
        (issue #1729 follow-up)."""
        _make_project(tmp_path, populate_rules=True)
        _hand_authored_claude_md(tmp_path)

        compiler = AgentsCompiler(str(tmp_path))
        config = CompilationConfig(
            target="claude",
            clean_orphaned=False,
            dry_run=False,
        )
        primitives = _make_primitives(tmp_path)
        result = compiler._compile_claude_md(config, primitives)

        assert not any("Skipped removal" in w for w in result.warnings), (
            "Plain compile (no --clean) must not emit 'Skipped removal' warnings; "
            f"got: {result.warnings}"
        )

    def test_plain_compile_apm_generated_emits_no_stale_warnings(self, tmp_path):
        """Plain apm compile (no --clean) with an APM-generated CLAUDE.md must
        emit NO stale-file warnings and must NOT read CLAUDE.md at all
        (issue #1729 comment M: live block must be a no-op without --clean)."""
        _make_project(tmp_path, populate_rules=True)
        _apm_generated_claude_md(tmp_path)

        compiler = AgentsCompiler(str(tmp_path))
        config = CompilationConfig(
            target="claude",
            clean_orphaned=False,
            dry_run=False,
        )
        primitives = _make_primitives(tmp_path)
        result = compiler._compile_claude_md(config, primitives)

        assert not any(
            any(kw in w for kw in ("stale", "Skipped removal", "Could not read", "hand-authored"))
            for w in result.warnings
        ), f"Plain compile (no --clean) must emit no stale-file warnings; got: {result.warnings}"


# ---------------------------------------------------------------------------
# Clean-checkout behavior from #1138 unchanged
# ---------------------------------------------------------------------------


class TestCleanCheckoutBehaviorUnchanged:
    """When .claude/rules/ is already populated and no CLAUDE.md exists,
    _compile_claude_md must never create one (regression guard for #1138)."""

    def test_no_claude_md_created_when_rules_populated_and_no_existing_file(self, tmp_path):
        """No CLAUDE.md is created when .claude/rules/ is populated (clean checkout)."""
        _make_project(tmp_path, populate_rules=True)
        assert not (tmp_path / "CLAUDE.md").exists(), "precondition: no CLAUDE.md"

        compiler = AgentsCompiler(str(tmp_path))
        config = CompilationConfig(
            target="claude",
            clean_orphaned=False,
            dry_run=False,
        )
        primitives = _make_primitives(tmp_path)
        compiler._compile_claude_md(config, primitives)

        assert not (tmp_path / "CLAUDE.md").exists(), (
            "CLAUDE.md must NOT be created when .claude/rules/ is already populated (#1138)"
        )

    def test_no_claude_md_created_even_with_clean_flag(self, tmp_path):
        """--clean must not cause CLAUDE.md to be created either."""
        _make_project(tmp_path, populate_rules=True)
        assert not (tmp_path / "CLAUDE.md").exists(), "precondition: no CLAUDE.md"

        compiler = AgentsCompiler(str(tmp_path))
        config = CompilationConfig(
            target="claude",
            clean_orphaned=True,
            dry_run=False,
        )
        primitives = _make_primitives(tmp_path)
        compiler._compile_claude_md(config, primitives)

        assert not (tmp_path / "CLAUDE.md").exists(), (
            "CLAUDE.md must NOT be created even with --clean when .claude/rules/ is populated"
        )


# ---------------------------------------------------------------------------
# --no-dedup disables dedup -> no removal logic triggered
# ---------------------------------------------------------------------------


class TestNoDedupPreventsRemoval:
    """When --no-dedup is set, instructions are always written into CLAUDE.md
    and the stale-file-removal path must not fire."""

    def test_no_dedup_writes_claude_md_despite_rules_dir(self, tmp_path):
        """--no-dedup regenerates CLAUDE.md even when .claude/rules/ is populated;
        no removal must happen."""
        _make_project(tmp_path, populate_rules=True)
        # Start with an APM-generated file that could mistakenly be deleted
        _apm_generated_claude_md(tmp_path)

        compiler = AgentsCompiler(str(tmp_path))
        config = CompilationConfig(
            target="claude",
            clean_orphaned=True,
            no_dedup=True,
            dry_run=False,
        )
        primitives = _make_primitives(tmp_path)
        compiler._compile_claude_md(config, primitives)

        # File must still exist (now regenerated with full instructions)
        assert (tmp_path / "CLAUDE.md").exists(), (
            "--no-dedup must produce a CLAUDE.md; stale-removal must not fire"
        )
        body = (tmp_path / "CLAUDE.md").read_text(encoding="utf-8")
        assert "# Project Standards" in body or "global guidance" in body.lower(), (
            "--no-dedup CLAUDE.md must contain instruction content"
        )

    def test_no_dedup_does_not_remove_without_rules(self, tmp_path):
        """--no-dedup on a project with no .claude/rules/ writes CLAUDE.md normally."""
        _make_project(tmp_path, populate_rules=False)

        compiler = AgentsCompiler(str(tmp_path))
        config = CompilationConfig(
            target="claude",
            no_dedup=True,
            dry_run=False,
        )
        primitives = _make_primitives(tmp_path)
        result = compiler._compile_claude_md(config, primitives)

        assert result.success
        assert (tmp_path / "CLAUDE.md").exists()


# ---------------------------------------------------------------------------
# Dry-run must never mutate files and must preview stale-removal
# ---------------------------------------------------------------------------


class TestDryRunCleanBehavior:
    """apm compile --clean --dry-run must preview what would happen without
    touching the filesystem (issue #1729 follow-up)."""

    def test_dry_run_clean_leaves_apm_generated_file(self, tmp_path):
        """APM-generated CLAUDE.md + populated rules + clean_orphaned=True + dry_run=True
        -> file STILL EXISTS (dry-run must never delete)."""
        _make_project(tmp_path, populate_rules=True)
        _apm_generated_claude_md(tmp_path)

        compiler = AgentsCompiler(str(tmp_path))
        config = CompilationConfig(
            target="claude",
            clean_orphaned=True,
            dry_run=True,
        )
        primitives = _make_primitives(tmp_path)
        result = compiler._compile_claude_md(config, primitives)

        assert result.success, f"Expected success, got errors: {result.errors}"
        assert (tmp_path / "CLAUDE.md").exists(), (
            "dry-run must NEVER delete the stale CLAUDE.md -- only preview the removal"
        )

    def test_dry_run_clean_preview_mentions_stale_removal(self, tmp_path):
        """Dry-run output must include a line saying the stale CLAUDE.md would
        be removed (so users know --clean would act on it)."""
        _make_project(tmp_path, populate_rules=True)
        _apm_generated_claude_md(tmp_path)

        compiler = AgentsCompiler(str(tmp_path))
        config = CompilationConfig(
            target="claude",
            clean_orphaned=True,
            dry_run=True,
        )
        primitives = _make_primitives(tmp_path)
        result = compiler._compile_claude_md(config, primitives)

        assert "would remove stale CLAUDE.md" in result.content, (
            "Dry-run --clean preview must mention 'would remove stale CLAUDE.md'; "
            f"got content:\n{result.content}"
        )

    def test_dry_run_no_clean_does_not_preview_removal(self, tmp_path):
        """Dry-run WITHOUT --clean must NOT preview a stale-removal line
        (removal is not going to happen; the mention would be misleading)."""
        _make_project(tmp_path, populate_rules=True)
        _apm_generated_claude_md(tmp_path)

        compiler = AgentsCompiler(str(tmp_path))
        config = CompilationConfig(
            target="claude",
            clean_orphaned=False,
            dry_run=True,
        )
        primitives = _make_primitives(tmp_path)
        result = compiler._compile_claude_md(config, primitives)

        assert "would remove stale CLAUDE.md" not in result.content, (
            "Dry-run without --clean must not mention stale-removal; "
            f"got content:\n{result.content}"
        )

    def test_dry_run_clean_preview_emitted_via_logger(self, tmp_path):
        """The stale-removal preview must be emitted through self._log (progress)
        so it reaches the terminal on the distributed dry-run path.

        This is the regression test for issue #1729: cli.py does `pass` on
        dry-run success and never prints result.content, so the preview MUST
        arrive via the logger rather than relying solely on result.content.
        Without the fix this test would fail because no logger call is made.
        """
        _make_project(tmp_path, populate_rules=True)
        _apm_generated_claude_md(tmp_path)

        logger = _CapturingLogger()
        compiler = AgentsCompiler(str(tmp_path))
        compiler._logger = logger
        config = CompilationConfig(
            target="claude",
            clean_orphaned=True,
            dry_run=True,
        )
        primitives = _make_primitives(tmp_path)
        compiler._compile_claude_md(config, primitives)

        messages = [m for _, m in logger.logged]
        assert any("would remove stale" in m and "CLAUDE.md" in m for m in messages), (
            "Dry-run --clean must emit the stale-removal preview through the logger "
            "(not just in result.content) so it reaches the terminal via the distributed "
            "cli.py dry-run path. "
            f"Logger calls captured: {logger.logged}"
        )


# ---------------------------------------------------------------------------
# would_emit_no_claude_md guard: constitution case must NOT show removal preview
# ---------------------------------------------------------------------------


class TestConstitutionCaseNoRemovalPreview:
    """A project with a constitution emits a CLAUDE.md even when .claude/rules/
    is populated (the constitution block keeps the file alive). In that case
    would_emit_no_claude_md is False and no removal preview must appear."""

    def test_dry_run_clean_with_constitution_does_not_preview_removal(self, tmp_path):
        """Dry-run + --clean + .claude/rules/ populated + constitution present
        -> NO removal preview (CLAUDE.md would still be written for the constitution)."""
        _make_project(tmp_path, populate_rules=True)
        _apm_generated_claude_md(tmp_path)

        # Place a constitution at the canonical path so the formatter emits a CLAUDE.md.
        # The path is .specify/memory/constitution.md relative to base_dir.
        constitution_dir = tmp_path / ".specify" / "memory"
        constitution_dir.mkdir(parents=True)
        (constitution_dir / "constitution.md").write_text(
            "# Constitution\nBe helpful.\n", encoding="utf-8"
        )
        # Cache is reset before every test by the _reset_constitution_cache autouse fixture.

        compiler = AgentsCompiler(str(tmp_path))
        config = CompilationConfig(
            target="claude",
            clean_orphaned=True,
            dry_run=True,
        )
        primitives = _make_primitives(tmp_path)
        result = compiler._compile_claude_md(config, primitives)

        # With a constitution the content_map is non-empty (root CLAUDE.md is kept
        # for the constitution block), so would_emit_no_claude_md is False and the
        # removal preview block must NOT run.
        assert "would remove stale" not in result.content, (
            "When a constitution keeps CLAUDE.md alive, the dry-run --clean path "
            "must NOT show a stale-removal preview. "
            f"Got content:\n{result.content}"
        )


# ---------------------------------------------------------------------------
# Dry-run hand-authored CLAUDE.md: preview that deletion would be skipped
# ---------------------------------------------------------------------------


class TestDryRunHandAuthoredPreview:
    """apm compile --clean --dry-run with a hand-authored CLAUDE.md must surface
    a preview/warning that the file would NOT be deleted (issue #1729 follow-up,
    comment I: dry-run was previously silent for the hand-authored case)."""

    def test_dry_run_clean_hand_authored_leaves_file(self, tmp_path):
        """--clean --dry-run must NEVER delete a hand-authored CLAUDE.md."""
        _make_project(tmp_path, populate_rules=True)
        _hand_authored_claude_md(tmp_path)
        original_content = (tmp_path / "CLAUDE.md").read_text(encoding="utf-8")

        compiler = AgentsCompiler(str(tmp_path))
        config = CompilationConfig(
            target="claude",
            clean_orphaned=True,
            dry_run=True,
        )
        primitives = _make_primitives(tmp_path)
        result = compiler._compile_claude_md(config, primitives)

        assert result.success, f"Expected success, got errors: {result.errors}"
        assert (tmp_path / "CLAUDE.md").exists(), (
            "--clean --dry-run must NEVER delete the hand-authored CLAUDE.md"
        )
        assert (tmp_path / "CLAUDE.md").read_text(encoding="utf-8") == original_content, (
            "Hand-authored CLAUDE.md content must be unchanged after --clean --dry-run"
        )

    def test_dry_run_clean_hand_authored_emits_warning(self, tmp_path):
        """--clean --dry-run must emit a warning that the hand-authored file
        would NOT be deleted, so users are not surprised by the live outcome."""
        _make_project(tmp_path, populate_rules=True)
        _hand_authored_claude_md(tmp_path)

        compiler = AgentsCompiler(str(tmp_path))
        config = CompilationConfig(
            target="claude",
            clean_orphaned=True,
            dry_run=True,
        )
        primitives = _make_primitives(tmp_path)
        result = compiler._compile_claude_md(config, primitives)

        assert any("hand-authored" in w for w in result.warnings), (
            "Dry-run --clean with a hand-authored CLAUDE.md must emit a 'hand-authored'"
            f" warning; got: {result.warnings}"
        )

    def test_dry_run_clean_hand_authored_preview_in_content(self, tmp_path):
        """The dry-run content must include the skip-preview line mentioning
        'hand-authored' so users see it when result.content is printed."""
        _make_project(tmp_path, populate_rules=True)
        _hand_authored_claude_md(tmp_path)

        compiler = AgentsCompiler(str(tmp_path))
        config = CompilationConfig(
            target="claude",
            clean_orphaned=True,
            dry_run=True,
        )
        primitives = _make_primitives(tmp_path)
        result = compiler._compile_claude_md(config, primitives)

        assert "hand-authored" in result.content, (
            "Dry-run --clean preview content must mention 'hand-authored' for a"
            f" hand-authored CLAUDE.md; got content:\n{result.content}"
        )

    def test_dry_run_clean_hand_authored_preview_emitted_via_logger(self, tmp_path):
        """The hand-authored skip preview must also be emitted through self._log
        so it reaches the terminal on the distributed dry-run path (issue #1729
        comment N: hand-authored case was previously log-silent)."""
        _make_project(tmp_path, populate_rules=True)
        _hand_authored_claude_md(tmp_path)

        logger = _CapturingLogger()
        compiler = AgentsCompiler(str(tmp_path))
        compiler._logger = logger
        config = CompilationConfig(
            target="claude",
            clean_orphaned=True,
            dry_run=True,
        )
        primitives = _make_primitives(tmp_path)
        compiler._compile_claude_md(config, primitives)

        messages = [m for _, m in logger.logged]
        assert any("hand-authored" in m for m in messages), (
            "Dry-run --clean with a hand-authored CLAUDE.md must emit the skip-preview "
            "through the logger (not just in result.content) so it reaches the terminal "
            "via the distributed cli.py dry-run path. "
            f"Logger calls captured: {logger.logged}"
        )


# ---------------------------------------------------------------------------
# Dry-run read-error: preview emitted via logger (issue #1729 comment N)
# ---------------------------------------------------------------------------


class TestDryRunReadErrorLoggedViaLogger:
    """apm compile --clean --dry-run with an unreadable CLAUDE.md must surface
    the read-error through the logger so users see it on the distributed dry-run
    path (issue #1729 comment N)."""

    def test_dry_run_clean_read_error_emitted_via_logger(self, tmp_path):
        """When CLAUDE.md exists but cannot be decoded as UTF-8, the dry-run --clean
        path must emit the read-error at warning level through the logger.

        Uses an invalid-UTF-8 byte sequence to deterministically trigger
        UnicodeDecodeError (caught by _detect_stale_claude_md) across all
        environments including containers running as root (where chmod(0o000) is
        unreliable).  This also exercises the UnicodeDecodeError branch added by
        comment P.
        """
        _make_project(tmp_path, populate_rules=True)
        claude_md = tmp_path / "CLAUDE.md"
        # Write bytes that are not valid UTF-8 -- read_text(encoding="utf-8") will
        # raise UnicodeDecodeError regardless of filesystem permissions or user id.
        claude_md.write_bytes(b"\xff\xfe invalid utf-8 \x80\x81")

        logger = _CapturingLogger()
        compiler = AgentsCompiler(str(tmp_path))
        compiler._logger = logger
        config = CompilationConfig(
            target="claude",
            clean_orphaned=True,
            dry_run=True,
        )
        primitives = _make_primitives(tmp_path)
        result = compiler._compile_claude_md(config, primitives)

        warning_messages = [m for level, m in logger.logged if level == "warning"]
        assert any("Could not read" in m for m in warning_messages), (
            "Dry-run --clean with an undecodable CLAUDE.md must emit a 'Could not read' "
            "warning through the logger (not just in result.warnings) so it reaches "
            "the terminal via the distributed cli.py dry-run path. "
            f"Logger calls captured: {logger.logged}"
        )
        assert any("Could not read" in w for w in result.warnings), (
            f"result.warnings must also contain the read-error; got: {result.warnings}"
        )
