"""Acceptance tests for issue #1730: apm compile writes empty AGENTS.md shells.

All tests in this module correspond to the acceptance criteria from the issue:

  Case A -- root AGENTS.md (global instructions)
  Case B -- distributed subdir AGENTS.md (scoped instructions)
  --clean removes pre-existing APM-generated empty shells
  Hand-authored AGENTS.md (no marker) never deleted by --clean
  Plain `apm compile` stays non-destructive (suppresses new writes only)
  Multi-target (Codex/OpenCode/Windsurf/Gemini) unaffected
  --no-dedup / --force-instructions still produces full AGENTS.md
  INFO-style "not generated" message emitted

Mutation check: tests are written so that removing the empty-shell guard in
distributed_compiler.py or agents_compiler.py causes them to fail.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from apm_cli.compilation.agents_compiler import AgentsCompiler, CompilationConfig
from apm_cli.compilation.distributed_compiler import (
    AGENTS_MD_GENERATED_MARKER,
    DistributedAgentsCompiler,
    PlacementResult,
)
from apm_cli.primitives.models import Instruction, PrimitiveCollection

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _make_instruction(
    name: str,
    content: str = "Follow these rules.",
    apply_to: str | None = None,
    file_path: Path | None = None,
    tmp_path: Path | None = None,
) -> Instruction:
    if file_path is None:
        # Derive a tmp_path-scoped path so each test invocation gets a unique,
        # isolated location -- no shared temp-dir collisions across xdist workers
        # and no stale files between runs.
        if tmp_path is None:
            raise ValueError("Either file_path or tmp_path must be provided to _make_instruction")
        file_path = tmp_path / f"{name}.instructions.md"
    return Instruction(
        name=name,
        file_path=file_path,
        description=f"{name} instruction",
        apply_to=apply_to,
        content=content,
        author="test",
        source="local",
    )


def _make_primitives(*instructions: Instruction) -> PrimitiveCollection:
    col = PrimitiveCollection()
    for inst in instructions:
        col.add_primitive(inst)
    return col


def _apm_generated_marker_content(extra: str = "") -> str:
    """Produce minimal APM-generated AGENTS.md content (marker present)."""
    return (
        f"# AGENTS.md\n"
        f"{AGENTS_MD_GENERATED_MARKER}\n"
        f"<!-- Build ID: abc123def456 -->\n"
        f"<!-- APM Version: 0.0.0 -->\n"
        f"\n"
        f"---\n"
        f"*This file was generated by APM CLI. Do not edit manually.*\n"
        f"*To regenerate: `apm compile`*\n"
        f"{extra}\n"
    )


# ---------------------------------------------------------------------------
# Case A: root AGENTS.md with global instructions already in .github/instructions/
# ---------------------------------------------------------------------------


class TestCaseAGlobalInstructions:
    """Case A: copilot target (internal alias `vscode`), .github/instructions/*.md present -> NO root AGENTS.md."""

    @pytest.fixture
    def project_global(self, tmp_path: Path):
        """Project with a global (no applyTo) instruction, .github/instructions/ populated."""
        # Write instruction primitive
        instr_dir = tmp_path / ".apm" / "instructions"
        instr_dir.mkdir(parents=True)
        instr_file = instr_dir / "global.instructions.md"
        instr_file.write_text(
            "---\ndescription: A global instruction\n---\n"
            "This is global guidance that should reach Copilot.\n",
            encoding="utf-8",
        )

        # Deploy to .github/instructions/ (simulates `apm install`)
        gh_instr_dir = tmp_path / ".github" / "instructions"
        gh_instr_dir.mkdir(parents=True)
        (gh_instr_dir / "global.instructions.md").write_text(
            "---\ndescription: A global instruction\n---\n"
            "This is global guidance that should reach Copilot.\n",
            encoding="utf-8",
        )

        instruction = _make_instruction(
            name="global",
            content="This is global guidance that should reach Copilot.",
            apply_to=None,
            file_path=instr_file,
        )
        primitives = _make_primitives(instruction)
        return tmp_path, primitives

    def test_case_a_no_root_agents_md_written(self, project_global):
        """Failing-without-fix: copilot target (internal alias `vscode`) + .github/instructions/ -> NO root AGENTS.md."""
        tmp_path, primitives = project_global
        compiler = AgentsCompiler(str(tmp_path))
        config = CompilationConfig(target="vscode", dry_run=False)

        compiler._compile_distributed(config, primitives)

        agents_md = tmp_path / "AGENTS.md"
        assert not agents_md.exists(), (
            "AGENTS.md must NOT be created when instructions are already in"
            " .github/instructions/ and the body would be empty.\n"
            f"Content written:\n{agents_md.read_text() if agents_md.exists() else '(none)'}"
        )

    def test_case_a_suppressed_path_in_result(self, project_global):
        """suppressed_empty_paths is populated in the distributed result."""
        from apm_cli.compilation.distributed_compiler import DistributedAgentsCompiler

        tmp_path, primitives = project_global
        dist_compiler = DistributedAgentsCompiler(str(tmp_path))
        config = {
            "skip_instructions": True,
            "source_attribution": False,
            "clean_orphaned": False,
            "dry_run": False,
            "debug": False,
        }
        result = dist_compiler.compile_distributed(primitives, config=config)
        assert result.success
        assert len(result.suppressed_empty_paths) > 0, (
            "suppressed_empty_paths must be non-empty when dedup fires and placement"
            " would be an empty shell"
        )

    def test_case_a_no_dedup_still_writes_agents_md(self, project_global):
        """--no-dedup must always produce AGENTS.md even with .github/instructions/ present."""
        tmp_path, primitives = project_global
        compiler = AgentsCompiler(str(tmp_path))
        config = CompilationConfig(target="vscode", no_dedup=True, dry_run=False)

        compiler._compile_distributed(config, primitives)

        agents_md = tmp_path / "AGENTS.md"
        assert agents_md.exists(), (
            "AGENTS.md must be written when --no-dedup is set, regardless of"
            " .github/instructions/ state."
        )
        body = agents_md.read_text(encoding="utf-8")
        assert "global guidance" in body, (
            "--no-dedup must include instruction content in AGENTS.md. Got:\n" + body
        )


# ---------------------------------------------------------------------------
# Case B: distributed subdir AGENTS.md (scoped instructions)
# ---------------------------------------------------------------------------


class TestCaseBScopedInstructions:
    """Case B: scoped instructions already in .github/instructions/ -> NO subdir AGENTS.md."""

    @pytest.fixture
    def project_scoped(self, tmp_path: Path):
        """Project with scoped instructions (docs/**/*.md, src/**/*.py) deployed to .github/."""
        # Create source files
        (tmp_path / "docs").mkdir()
        (tmp_path / "docs" / "readme.md").write_text("# doc", encoding="utf-8")
        (tmp_path / "src").mkdir()
        (tmp_path / "src" / "main.py").write_text("x = 1", encoding="utf-8")

        instr_dir = tmp_path / ".apm" / "instructions"
        instr_dir.mkdir(parents=True)

        docs_file = instr_dir / "docs.instructions.md"
        docs_file.write_text(
            "---\ndescription: Markdown docs\napplyTo: 'docs/**/*.md'\n---\n"
            "Docs writing guidance.\n",
            encoding="utf-8",
        )
        src_file = instr_dir / "src.instructions.md"
        src_file.write_text(
            "---\ndescription: Python source\napplyTo: 'src/**/*.py'\n---\n"
            "Python coding guidance.\n",
            encoding="utf-8",
        )

        # Deploy to .github/instructions/
        gh_instr_dir = tmp_path / ".github" / "instructions"
        gh_instr_dir.mkdir(parents=True)
        (gh_instr_dir / "docs.instructions.md").write_text(
            docs_file.read_text(encoding="utf-8"), encoding="utf-8"
        )
        (gh_instr_dir / "src.instructions.md").write_text(
            src_file.read_text(encoding="utf-8"), encoding="utf-8"
        )

        docs_inst = _make_instruction(
            name="docs",
            content="Docs writing guidance.",
            apply_to="docs/**/*.md",
            file_path=docs_file,
        )
        src_inst = _make_instruction(
            name="src",
            content="Python coding guidance.",
            apply_to="src/**/*.py",
            file_path=src_file,
        )
        primitives = _make_primitives(docs_inst, src_inst)
        return tmp_path, primitives

    def test_case_b_no_subdir_agents_md_written(self, project_scoped):
        """Failing-without-fix: no docs/AGENTS.md or src/AGENTS.md when dedup fires."""
        tmp_path, primitives = project_scoped
        compiler = AgentsCompiler(str(tmp_path))
        config = CompilationConfig(target="vscode", dry_run=False)

        compiler._compile_distributed(config, primitives)

        docs_agents_md = tmp_path / "docs" / "AGENTS.md"
        src_agents_md = tmp_path / "src" / "AGENTS.md"

        assert not docs_agents_md.exists(), (
            "docs/AGENTS.md must NOT be created when instructions are already in"
            " .github/instructions/ and the body would be empty."
        )
        assert not src_agents_md.exists(), (
            "src/AGENTS.md must NOT be created when instructions are already in"
            " .github/instructions/ and the body would be empty."
        )

    def test_case_b_multiple_suppressed_paths(self, project_scoped):
        """suppressed_empty_paths contains both docs and src entries."""
        from apm_cli.compilation.distributed_compiler import DistributedAgentsCompiler

        tmp_path, primitives = project_scoped
        dist_compiler = DistributedAgentsCompiler(str(tmp_path))
        config = {
            "skip_instructions": True,
            "source_attribution": False,
            "clean_orphaned": False,
            "dry_run": False,
            "debug": False,
        }
        result = dist_compiler.compile_distributed(primitives, config=config)
        assert result.success
        # At least the subdir placements (docs/AGENTS.md, src/AGENTS.md) should
        # be suppressed; root may or may not be in the placement depending on
        # context optimizer decisions.
        assert len(result.suppressed_empty_paths) >= 1


# ---------------------------------------------------------------------------
# INFO log message
# ---------------------------------------------------------------------------


class TestInfoLogMessage:
    """AGENTS.md not generated: INFO message emitted via the CommandLogger."""

    def test_info_message_logged_when_suppression_fires(self, tmp_path: Path):
        """When dedup suppresses all placements, an INFO-style log is emitted."""
        # Create .github/instructions/ with a markdown file
        gh_instr_dir = tmp_path / ".github" / "instructions"
        gh_instr_dir.mkdir(parents=True)
        (gh_instr_dir / "global.instructions.md").write_text(
            "---\ndescription: Global\n---\nGlobal guidance.\n",
            encoding="utf-8",
        )

        # Write the source instruction on disk so the fixture mirrors real
        # project state and stays hermetic if filesystem-based validation tightens.
        apm_instr_dir = tmp_path / ".apm" / "instructions"
        apm_instr_dir.mkdir(parents=True)
        apm_instr_file = apm_instr_dir / "global.instructions.md"
        apm_instr_file.write_text(
            "---\ndescription: Global\n---\nGlobal guidance.\n",
            encoding="utf-8",
        )

        instruction = _make_instruction(
            name="global",
            content="Global guidance.",
            apply_to=None,
            file_path=apm_instr_file,
        )
        primitives = _make_primitives(instruction)

        # Capture log calls via a mock logger
        logged_messages: list[str] = []

        class _MockLogger:
            def progress(self, msg, **_kw):
                logged_messages.append(msg)

            def warning(self, msg, **_kw):  # no-op stub
                pass

            def error(self, msg, **_kw):  # no-op stub
                pass

            def success(self, msg, **_kw):  # no-op stub
                pass

        compiler = AgentsCompiler(str(tmp_path))
        config = CompilationConfig(target="vscode", dry_run=False)
        result = compiler.compile(config, primitives, logger=_MockLogger())

        assert result.success
        assert any("not generated" in m and "instructions/" in m for m in logged_messages), (
            "Expected INFO message containing 'not generated' and 'instructions/'.\n"
            f"Logged messages: {logged_messages}"
        )


# ---------------------------------------------------------------------------
# --clean removes pre-existing empty shells
# ---------------------------------------------------------------------------


class TestCleanRemovesEmptyShells:
    """apm compile --clean removes pre-existing APM-generated empty AGENTS.md shells."""

    @pytest.fixture
    def project_with_stale_shell(self, tmp_path: Path):
        """Project where a previous run left an empty-shell AGENTS.md."""
        # Create .github/instructions/ with deployed instructions
        gh_instr_dir = tmp_path / ".github" / "instructions"
        gh_instr_dir.mkdir(parents=True)
        (gh_instr_dir / "global.instructions.md").write_text(
            "---\ndescription: Global\n---\nGlobal guidance.\n",
            encoding="utf-8",
        )

        # Stale empty shell from a previous run (has APM marker)
        stale_shell = tmp_path / "AGENTS.md"
        stale_shell.write_text(_apm_generated_marker_content(), encoding="utf-8")

        # Write the source instruction on disk so the fixture is hermetic against
        # future filesystem-based validation tightening.
        apm_instr_dir = tmp_path / ".apm" / "instructions"
        apm_instr_dir.mkdir(parents=True)
        apm_instr_file = apm_instr_dir / "global.instructions.md"
        apm_instr_file.write_text(
            "---\ndescription: Global\n---\nGlobal guidance.\n",
            encoding="utf-8",
        )

        instruction = _make_instruction(
            name="global",
            content="Global guidance.",
            apply_to=None,
            file_path=apm_instr_file,
        )
        primitives = _make_primitives(instruction)
        return tmp_path, primitives, stale_shell

    def test_clean_removes_stale_apm_generated_shell(self, project_with_stale_shell):
        """--clean removes APM-generated AGENTS.md shells left by a prior run."""
        tmp_path, primitives, stale_shell = project_with_stale_shell
        compiler = AgentsCompiler(str(tmp_path))
        config = CompilationConfig(target="vscode", clean_orphaned=True, dry_run=False)

        compiler._compile_distributed(config, primitives)

        assert not stale_shell.exists(), (
            "Stale APM-generated empty-shell AGENTS.md must be removed by --clean."
        )

    def test_plain_compile_leaves_stale_shell(self, project_with_stale_shell):
        """Plain `apm compile` (without --clean) does NOT delete pre-existing empty shells."""
        tmp_path, primitives, stale_shell = project_with_stale_shell
        compiler = AgentsCompiler(str(tmp_path))
        config = CompilationConfig(target="vscode", clean_orphaned=False, dry_run=False)

        compiler._compile_distributed(config, primitives)

        # The stale shell should still exist (non-destructive by default)
        assert stale_shell.exists(), (
            "Plain `apm compile` must NOT delete pre-existing AGENTS.md files."
        )


# ---------------------------------------------------------------------------
# Hand-authored AGENTS.md protection
# ---------------------------------------------------------------------------


class TestHandAuthoredProtection:
    """Hand-authored AGENTS.md (no APM marker) is never deleted by --clean."""

    def test_hand_authored_not_deleted_by_clean(self, tmp_path: Path):
        """--clean must not delete hand-authored AGENTS.md (no APM marker)."""
        # Deploy instructions
        gh_instr_dir = tmp_path / ".github" / "instructions"
        gh_instr_dir.mkdir(parents=True)
        (gh_instr_dir / "global.instructions.md").write_text(
            "---\ndescription: Global\n---\nGlobal guidance.\n",
            encoding="utf-8",
        )

        # Hand-authored AGENTS.md with no APM marker
        hand_authored = tmp_path / "AGENTS.md"
        hand_authored.write_text(
            "# My Custom Agent Guide\nThis file was written by hand.\n",
            encoding="utf-8",
        )

        apm_instr_dir = tmp_path / ".apm" / "instructions"
        apm_instr_dir.mkdir(parents=True)
        apm_instr_file = apm_instr_dir / "global.instructions.md"
        apm_instr_file.write_text(
            "---\ndescription: Global\n---\nGlobal guidance.\n",
            encoding="utf-8",
        )

        instruction = _make_instruction(
            name="global",
            content="Global guidance.",
            apply_to=None,
            file_path=apm_instr_file,
        )
        primitives = _make_primitives(instruction)

        compiler = AgentsCompiler(str(tmp_path))
        config = CompilationConfig(target="vscode", clean_orphaned=True, dry_run=False)
        compiler._compile_distributed(config, primitives)

        assert hand_authored.exists(), (
            "Hand-authored AGENTS.md (no APM marker) must NEVER be deleted by --clean."
        )
        assert "written by hand" in hand_authored.read_text(encoding="utf-8"), (
            "Hand-authored AGENTS.md content must not be modified."
        )


# ---------------------------------------------------------------------------
# Multi-target: Codex / OpenCode / Windsurf unaffected
# ---------------------------------------------------------------------------


class TestMultiTargetUnaffected:
    """Non-Copilot targets (Codex, OpenCode, Windsurf) never trigger suppression."""

    @pytest.fixture
    def project_with_github_instructions(self, tmp_path: Path):
        """Project with .github/instructions/ populated + primitives."""
        gh_instr_dir = tmp_path / ".github" / "instructions"
        gh_instr_dir.mkdir(parents=True)
        (gh_instr_dir / "style.instructions.md").write_text(
            "---\ndescription: Style\n---\nUse type hints.\n",
            encoding="utf-8",
        )

        apm_instr_dir = tmp_path / ".apm" / "instructions"
        apm_instr_dir.mkdir(parents=True)
        apm_instr_file = apm_instr_dir / "style.instructions.md"
        apm_instr_file.write_text(
            "---\ndescription: Style\napplyTo: '**/*.py'\n---\nUse type hints.\n",
            encoding="utf-8",
        )

        instruction = _make_instruction(
            name="style",
            content="Use type hints.",
            apply_to="**/*.py",
            file_path=apm_instr_file,
        )
        primitives = _make_primitives(instruction)
        return tmp_path, primitives

    @pytest.mark.parametrize("target", ["codex", "opencode", "windsurf"])
    def test_non_copilot_target_writes_agents_md_with_instructions(
        self, project_with_github_instructions, target
    ):
        """Codex/OpenCode/Windsurf: instructions must appear in AGENTS.md even when
        .github/instructions/ is populated (they do not read that location)."""
        tmp_path, primitives = project_with_github_instructions
        compiler = AgentsCompiler(str(tmp_path))
        config = CompilationConfig(target=target, dry_run=False)

        compiler._compile_distributed(config, primitives)

        agents_md = tmp_path / "AGENTS.md"
        assert agents_md.exists(), (
            f"AGENTS.md must be created for {target} target even with"
            " .github/instructions/ present."
        )
        body = agents_md.read_text(encoding="utf-8")
        assert "Use type hints" in body, (
            f"{target} target must include instructions in AGENTS.md. Got:\n" + body
        )

    def test_multi_target_frozenset_with_non_copilot_writes_instructions(
        self, project_with_github_instructions
    ):
        """frozenset({'vscode', 'agents'}) must NOT dedup because 'agents' family
        may include non-copilot consumers."""
        tmp_path, primitives = project_with_github_instructions
        compiler = AgentsCompiler(str(tmp_path))
        config = CompilationConfig(
            target=frozenset({"vscode", "agents"}),
            dry_run=False,
        )

        compiler._compile_distributed(config, primitives)

        agents_md = tmp_path / "AGENTS.md"
        assert agents_md.exists()
        body = agents_md.read_text(encoding="utf-8")
        assert "Use type hints" in body


# ---------------------------------------------------------------------------
# _is_placement_empty_shell unit tests
# ---------------------------------------------------------------------------


class TestIsPlacementEmptyShell:
    """Unit tests for DistributedAgentsCompiler._is_placement_empty_shell.

    This method is only called when skip_instructions=True (instructions already
    in .github/instructions/).  Given that, it answers: "would this placement
    still carry non-empty content?"  The only remaining content source is a
    constitution file injected at write time.

    The method is model-based: it consults the constitution file on disk (gated
    by with_constitution) rather than parsing rendered content strings.
    """

    @pytest.fixture
    def compiler(self, tmp_path: Path) -> DistributedAgentsCompiler:
        from unittest.mock import MagicMock, patch

        mock_opt = MagicMock()
        mock_lr = MagicMock()
        mock_fmt = MagicMock()
        with (
            patch(
                "apm_cli.compilation.distributed_compiler.ContextOptimizer",
                return_value=mock_opt,
            ),
            patch(
                "apm_cli.compilation.distributed_compiler.UnifiedLinkResolver",
                return_value=mock_lr,
            ),
            patch(
                "apm_cli.compilation.distributed_compiler.CompilationFormatter",
                return_value=mock_fmt,
            ),
        ):
            c = DistributedAgentsCompiler(base_dir=str(tmp_path))
        c.context_optimizer = mock_opt
        c.link_resolver = mock_lr
        c.output_formatter = mock_fmt
        return c

    def _make_placement(self, agents_path: Path, instructions=None) -> PlacementResult:
        return PlacementResult(
            agents_path=agents_path,
            instructions=instructions if instructions is not None else [],
        )

    def _write_constitution(self, base_dir: Path) -> Path:
        """Create a real constitution file at the canonical path under base_dir."""
        constitution_path = base_dir / ".specify" / "memory" / "constitution.md"
        constitution_path.parent.mkdir(parents=True, exist_ok=True)
        constitution_path.write_text("# Constitution content\n", encoding="utf-8")
        return constitution_path

    def test_empty_shell_no_constitution(self, compiler, tmp_path: Path):
        """When skip_instructions=True and no constitution file exists, placement is an empty shell.

        No constitution file is created; find_constitution(dir).is_file() returns False.
        """
        placement = self._make_placement(tmp_path / "AGENTS.md")
        # No constitution file created -> find_constitution(...).is_file() is False
        assert compiler._is_placement_empty_shell(placement) is True

    def test_empty_shell_even_with_instructions_present(self, compiler, tmp_path: Path):
        """When skip_instructions=True, instructions are not written; no constitution -> shell.

        The presence of instructions in the model does not prevent suppression:
        skip_instructions=True means those instructions will be omitted from output.
        No constitution file is created; find_constitution(dir).is_file() returns False.
        """
        inst = _make_instruction("style", content="Use type hints.", tmp_path=tmp_path)
        placement = self._make_placement(tmp_path / "AGENTS.md", instructions=[inst])
        # No constitution file created -> find_constitution(...).is_file() is False;
        # instructions present but skip_instructions=True means they won't be written
        assert compiler._is_placement_empty_shell(placement) is True

    def test_constitution_present_not_shell(self, compiler, tmp_path: Path):
        """Constitution file exists on disk + with_constitution=True -> NOT an empty shell."""
        placement = self._make_placement(tmp_path / "AGENTS.md")
        self._write_constitution(tmp_path)
        assert compiler._is_placement_empty_shell(placement) is False

    def test_no_constitution_with_constitution_false(self, compiler, tmp_path: Path):
        """with_constitution=False + constitution on disk -> still an empty shell.

        This is the predicate/writer disagreement fix (issue #1730):
        when --no-constitution is passed, the writer skips injection regardless
        of what is on disk, so the predicate must agree and return True.
        The with_constitution=False short-circuit fires before any filesystem check.
        """
        placement = self._make_placement(tmp_path / "AGENTS.md")
        self._write_constitution(tmp_path)
        # Even though constitution file exists, with_constitution=False means writer
        # will skip it -- placement is still an empty shell.
        assert compiler._is_placement_empty_shell(placement, with_constitution=False) is True

    def test_constitution_present_with_constitution_true_not_shell(self, compiler, tmp_path: Path):
        """Constitution file present on disk + with_constitution=True -> NOT an empty shell."""
        placement = self._make_placement(tmp_path / "AGENTS.md")
        self._write_constitution(tmp_path)
        assert compiler._is_placement_empty_shell(placement, with_constitution=True) is False


# ---------------------------------------------------------------------------
# Formatter guard: no contradictory output in fully-suppressed case (Fix 1)
# ---------------------------------------------------------------------------


class TestFormatterGuardFullySuppressed:
    """In the fully-suppressed case, the placement-table formatter output must be
    suppressed so the terminal doesn't print 'placing N files' immediately before
    'AGENTS.md not generated (N files)'."""

    def test_no_placement_table_when_fully_suppressed(self, tmp_path: Path):
        """Placement formatter output absent when ALL placements are suppressed.

        Uses compile() with a mock logger to exercise the full path including
        the logger assignment (_compile_distributed reads self._logger which is
        set by compile()).
        """
        # Setup: .github/instructions/ populated, one instruction, no constitution
        gh_instr_dir = tmp_path / ".github" / "instructions"
        gh_instr_dir.mkdir(parents=True)
        (gh_instr_dir / "global.instructions.md").write_text(
            "---\ndescription: Global\n---\nGlobal guidance.\n",
            encoding="utf-8",
        )

        # Write the source instruction on disk so the test is hermetic against
        # future filesystem-based validation tightening.
        apm_instr_dir = tmp_path / ".apm" / "instructions"
        apm_instr_dir.mkdir(parents=True)
        apm_instr_file = apm_instr_dir / "global.instructions.md"
        apm_instr_file.write_text(
            "---\ndescription: Global\n---\nGlobal guidance.\n",
            encoding="utf-8",
        )

        instruction = _make_instruction(
            name="global",
            content="Global guidance.",
            apply_to=None,
            file_path=apm_instr_file,
        )
        primitives = _make_primitives(instruction)

        from unittest.mock import MagicMock

        logged_messages: list[str] = []
        format_default_called: list = []

        class _MockLogger:
            def progress(self, msg, **_kw):
                logged_messages.append(msg)

            def warning(self, msg, **_kw):  # no-op stub
                pass

            def error(self, msg, **_kw):  # no-op stub
                pass

            def success(self, msg, **_kw):  # no-op stub
                pass

        mock_formatter = MagicMock()
        mock_formatter.format_default.side_effect = lambda r: (
            format_default_called.append(r) or "FORMATTER OUTPUT"
        )

        from apm_cli.compilation import distributed_compiler as dc_mod

        original_init = dc_mod.DistributedAgentsCompiler.__init__

        def patched_init(self_inner, *args, **kwargs):
            original_init(self_inner, *args, **kwargs)
            self_inner.output_formatter = mock_formatter

        import unittest.mock as um

        compiler = AgentsCompiler(str(tmp_path))
        config = CompilationConfig(target="vscode", dry_run=False)

        # Patch get_compilation_results_for_display to return something truthy so
        # we can confirm the guard suppresses the formatter call.
        mock_results = MagicMock()

        with um.patch.object(dc_mod.DistributedAgentsCompiler, "__init__", patched_init):
            with um.patch.object(
                dc_mod.DistributedAgentsCompiler,
                "get_compilation_results_for_display",
                return_value=mock_results,
            ):
                # Use compile() so that self._logger is populated via logger= arg
                compiler.compile(config, primitives, logger=_MockLogger())

        # The formatter must NOT have been called because all placements were suppressed
        assert format_default_called == [], (
            "format_default must NOT be called when all placements are suppressed.\n"
            f"It was called {len(format_default_called)} time(s)."
        )

        # But the INFO suppression message must still appear
        assert any("not generated" in m for m in logged_messages), (
            "INFO 'not generated' message must still appear even when formatter is suppressed.\n"
            f"Logged messages: {logged_messages}"
        )
